export { default as images } from "./images"

//PRODUCT CONSTS
export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST='PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS='PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL='PRODUCT_DETAILS_FAIL';

export const PRODUCT_CREATE_REQUEST='PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS='PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL='PRODUCT_CREATE_FAIL';

//CART CONSTS
export const CART_ADD_ITEM='CART_ADD_ITEM';
export const CART_REMOVE_ITEM='CART_REMOVE_ITEM';
export const CART_EMPTY="CART_EMPTY"

export const CART_SAVE_SHIPPING_ADDRESS="CART_SAVE_SHIPPING_ADDRESS"
export const CART_SAVE_PAYMENT_METHOD="CART_SAVE_PAYMENT_METHOD"
