export { default as images } from "./images"

//PRODUCT CONSTS
export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST='PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS='PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL='PRODUCT_DETAILS_FAIL';

export const PRODUCT_CREATE_REQUEST='PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS='PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL='PRODUCT_CREATE_FAIL';

//CART CONSTS
export const CART_ADD_ITEM='CART_ADD_ITEM';
export const CART_REMOVE_ITEM='CART_REMOVE_ITEM';
export const CART_EMPTY="CART_EMPTY"

export const CART_SAVE_SHIPPING_ADDRESS="CART_SAVE_SHIPPING_ADDRESS"
export const CART_SAVE_PAYMENT_METHOD="CART_SAVE_PAYMENT_METHOD"

//USER CONSTS
export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL';

export const USER_SIGNIN_REQUEST='USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS='USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL='USER_SIGNIN_FAIL';

export const USER_SIGNOUT='USER_SIGNOUT';

export const USER_DETAILS_REQUEST='USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS='USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL='USER_DETAILS_FAIL';
export const USER_DETAILS_RESET='USER_DETAILS_RESET';

export const USER_UPDATE_REQUEST='USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS='USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL='USER_UPDATE_FAIL';
export const USER_UPDATE_RESET='USER_UPDATE_RESET';

// ADMIN USER 
export const USER_LIST_REQUEST="USER_LIST_REQUEST"
export const USER_LIST_SUCCESS="USER_LIST_SUCCESS"
export const USER_LIST_FAIL="USER_LIST_FAIL"
export const USER_LIST_RESET="USER_LIST_RESET"

export const DELETE_USER_REQUEST='DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS='DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL='DELETE_USER_FAIL';

export const ADMIN_USER_UPDATE_REQUEST='ADMIN_USER_UPDATE_REQUEST';
export const ADMIN_USER_UPDATE_SUCCESS='ADMIN_USER_UPDATE_SUCCESS';
export const ADMIN_USER_UPDATE_FAIL='ADMIN_USER_UPDATE_FAIL';
export const ADMIN_USER_UPDATE_RESET='ADMIN_USER_UPDATE_RESET';



//ORDERS
export const ORDER_CREATE_REQUEST='ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS='ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL="ORDER_CREATE_FAIL"
export const ORDER_CREATE_RESET="ORDER_CREATE_RESET"

export const ORDER_DETAILS_REQUEST="ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS="ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL="ORDER_DETAILS_FAIL"

export const ORDER_PAY_REQUEST="ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS="ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL="ORDER_PAY_FAIL"
export const ORDER_PAY_RESET="ORDER_PAY_RESET"

export const ORDER_LIST_REQUEST="ORDER_LIST_REQUEST"
export const ORDER_LIST_SUCCESS="ORDER_LIST_SUCCESS"
export const ORDER_LIST_FAIL="ORDER_LIST_FAIL"

export const ORDER_MY_LIST_REQUEST="ORDER_MY_LIST_REQUEST"
export const ORDER_MY_LIST_SUCCESS="ORDER_MY_LIST_SUCCESS"
export const ORDER_MY_LIST_FAIL="ORDER_MY_LIST_FAIL"
export const ORDER_MY_LIST_RESET="ORDER_MY_LIST_RESET"



